project_name_override: kinexon-client   # distribution (PyPI/project)
package_name_override: kinexon_client  # importable package
class_name: KinexonClient
use_path_prefixes_for_title_model_names: true
package_version_override: 0.1.0
