name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  unit:
    name: Unit (no integration)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Create virtualenv
        run: uv venv

      - name: Install project (dev extras)
        run: uv pip install -e ".[dev]"

      - name: Run pytest with coverage (unit only)
        run: |
          uv run pytest -m "not integration" \
            --cov=kinexon_handball_api \
            --cov-report=term-missing \
            --cov-report=xml
